create table destinations (
	destination_id INT PRIMARY KEY AUTO_INCREMENT,
    country VARCHAR(50),
    city VARCHAR(50),
    description TEXT,
    category VARCHAR(30),
    ideal_season VARCHAR(20),
    avg_cost DECIMAL(10, 2),
    image_url VARCHAR(255)
);

create table activities (
	activity_id INT PRIMARY KEY AUTO_INCREMENT,
    destination_id INT,
    activity_name VARCHAR(100),
    activity_type VARCHAR(30),
    cost DECIMAL(10, 2),
    description TEXT,
    FOREIGN KEY (destination_id) REFERENCES destinations(destination_id)
);

create table reviews (
	review_id INT PRIMARY KEY AUTO_INCREMENT,
    destination_id INT,
    rating INT,
    review TEXT,
    FOREIGN KEY (destination_id) REFERENCES destinations(destination_id)
);


INSERT INTO destinations (country, city, description, category, ideal_season, avg_cost, image_url) VALUES
('France', 'Paris', 'The capital city of France, known for art, fashion, and the Eiffel Tower.', 'city', 'spring', 1200.00, 'https://example.com/paris.jpg'),
('Japan', 'Kyoto', 'Historic city famous for temples, shrines, and cherry blossoms.', 'cultural', 'spring', 900.00, 'https://example.com/kyoto.jpg'),
('Australia', 'Sydney', 'Known for the Sydney Opera House and stunning beaches.', 'beach', 'summer', 1500.00, 'https://example.com/sydney.jpg'),
('Italy', 'Rome', 'Historic city with landmarks like the Colosseum and Vatican City.', 'historical', 'fall', 1000.00, 'https://example.com/rome.jpg'),
('USA', 'New York', 'Famous for skyscrapers, Broadway, and cultural diversity.', 'city', 'fall', 1300.00, 'https://example.com/nyc.jpg'),
('Thailand', 'Bangkok', 'A bustling city famous for its temples, shopping, and street food.', 'city', 'winter', 800.00, 'https://example.com/bangkok.jpg'),
('Brazil', 'Rio de Janeiro', 'Famous for its beaches, Carnival, and the Christ the Redeemer statue.', 'beach', 'summer', 1400.00, 'https://example.com/rio.jpg'),
('Spain', 'Barcelona', 'A vibrant city known for its architecture, beaches, and art scene.', 'city', 'spring', 1100.00, 'https://example.com/barcelona.jpg'),
('Canada', 'Vancouver', 'A stunning city surrounded by mountains and ocean, perfect for outdoor lovers.', 'nature', 'summer', 1200.00, 'https://example.com/vancouver.jpg'),
('South Africa', 'Cape Town', 'Known for its beautiful landscapes, beaches, and Table Mountain.', 'nature', 'summer', 1000.00, 'https://example.com/capetown.jpg'),
('Egypt', 'Cairo', 'Famous for the Great Pyramids and the Sphinx.', 'historical', 'winter', 950.00, 'https://example.com/cairo.jpg'),
('USA', 'Los Angeles', 'Known for Hollywood, beaches, and entertainment industry landmarks.', 'city', 'summer', 1600.00, 'https://example.com/la.jpg'),
('Italy', 'Venice', 'Famous for its canals, gondola rides, and historic architecture.', 'historical', 'spring', 1200.00, 'https://example.com/venice.jpg'),
('India', 'Agra', 'Home of the Taj Mahal, one of the Seven Wonders of the World.', 'historical', 'winter', 700.00, 'https://example.com/agra.jpg'),
('Indonesia', 'Bali', 'Known for its beaches, rice terraces, and temples.', 'beach', 'summer', 800.00, 'https://example.com/bali.jpg'),
('Australia', 'Great Barrier Reef', 'A natural wonder famous for its coral reefs and marine life.', 'nature', 'winter', 1800.00, 'https://example.com/reef.jpg'),
('USA', 'Grand Canyon', 'A vast canyon in Arizona, known for its breathtaking views and hiking opportunities.', 'nature', 'spring', 700.00, 'https://example.com/grandcanyon.jpg'),
('Japan', 'Osaka', 'Known for its modern architecture, nightlife, and street food.', 'city', 'fall', 900.00, 'https://example.com/osaka.jpg'),
('Morocco', 'Marrakech', 'Famous for its markets, palaces, and vibrant culture.', 'cultural', 'spring', 750.00, 'https://example.com/marrakech.jpg'),
('New Zealand', 'Queenstown', 'A resort town known for adventure sports and stunning landscapes.', 'adventure', 'summer', 1300.00, 'https://example.com/queenstown.jpg'),
('Mexico', 'Cancun', 'Known for its beautiful beaches, resorts, and Mayan ruins.', 'beach', 'winter', 1100.00, 'https://example.com/cancun.jpg'),
('England', 'London', 'Famous for its history, landmarks, and cultural diversity.', 'city', 'spring', 1400.00, 'https://example.com/london.jpg'),
('Portugal', 'Lisbon', 'A charming city known for its historic neighborhoods and coastal views.', 'city', 'fall', 950.00, 'https://example.com/lisbon.jpg'),
('Greece', 'Santorini', 'Famous for its white-washed buildings, beaches, and sunsets.', 'beach', 'summer', 1200.00, 'https://example.com/santorini.jpg'),
('Vietnam', 'Hanoi', 'Known for its old quarter, lakes, and historical sites.', 'cultural', 'winter', 700.00, 'https://example.com/hanoi.jpg'),
('Kenya', 'Nairobi', 'Known for its wildlife, safaris, and proximity to national parks.', 'nature', 'summer', 1100.00, 'https://example.com/nairobi.jpg'),
('Turkey', 'Istanbul', 'A city that bridges Europe and Asia, known for its historic landmarks.', 'cultural', 'spring', 850.00, 'https://example.com/istanbul.jpg'),
('Scotland', 'Edinburgh', 'A city famous for its castles, festivals, and historic sites.', 'historical', 'summer', 1000.00, 'https://example.com/edinburgh.jpg');

INSERT INTO activities (destination_id, activity_name, activity_type, cost, description) VALUES
(1, 'Eiffel Tower Tour', 'sightseeing', 25.00, 'Explore the Eiffel Tower and enjoy panoramic views of Paris.'),
(1, 'Seine River Cruise', 'cruise', 45.00, 'A scenic cruise along the Seine River, with sights of Paris landmarks.'),
(2, 'Temple Hopping', 'cultural', 30.00, 'Visit famous temples like Kinkaku-ji and Fushimi Inari Shrine.'),
(2, 'Cherry Blossom Viewing', 'nature', 0.00, 'Enjoy the beautiful cherry blossoms in spring.'),
(3, 'Bondi Beach Surfing', 'adventure', 50.00, 'Surf the iconic waves at Bondi Beach in Sydney.'),
(3, 'Sydney Opera House Tour', 'sightseeing', 35.00, 'A guided tour of the Sydney Opera House.'),
(4, 'Colosseum Visit', 'historical', 20.00, 'Explore the ancient Colosseum, a symbol of Rome.'),
(4, 'Vatican Museum Tour', 'museum', 30.00, 'Discover art and history at the Vatican Museums.'),
(5, 'Central Park Walk', 'nature', 0.00, 'A peaceful walk through New York’s Central Park.'),
(5, 'Broadway Show', 'entertainment', 150.00, 'Watch a Broadway show in the Theater District of NYC.'),
(6, 'Grand Palace Visit', 'cultural', 20.00, 'Tour the historic Grand Palace and learn about Thailand’s royal history.'),
(6, 'Street Food Tour', 'food', 25.00, 'A guided food tour through Bangkok’s famous street markets.'),
(7, 'Christ the Redeemer Visit', 'sightseeing', 35.00, 'Visit the famous Christ the Redeemer statue and enjoy views of Rio.'),
(7, 'Carnival Parade', 'festival', 0.00, 'Experience the vibrant Rio Carnival parade in full swing.'),
(8, 'La Sagrada Familia Tour', 'sightseeing', 25.00, 'Visit the iconic La Sagrada Familia church and explore its architectural beauty.'),
(8, 'Beach Day at Barceloneta', 'beach', 0.00, 'Relax at Barceloneta Beach and enjoy the Mediterranean sun.'),
(9, 'Stanley Park Bike Ride', 'nature', 20.00, 'Explore Vancouver’s Stanley Park by bike, surrounded by natural beauty.'),
(9, 'Whale Watching Tour', 'adventure', 120.00, 'Go on a whale-watching tour off the coast of Vancouver.'),
(10, 'Table Mountain Hike', 'adventure', 0.00, 'Hike up Table Mountain and enjoy breathtaking views of Cape Town.'),
(10, 'Cape Point Tour', 'sightseeing', 45.00, 'Visit Cape Point and see the meeting point of the Atlantic and Indian Oceans.'),
(11, 'Pyramid Tour', 'sightseeing', 30.00, 'Visit the famous Pyramids of Giza and the Sphinx in Cairo.'),
(11, 'Nile River Cruise', 'cruise', 60.00, 'Cruise along the Nile River and see historic monuments.'),
(12, 'Hollywood Walk of Fame', 'sightseeing', 0.00, 'Stroll along Hollywood Boulevard and see the stars on the Walk of Fame.'),
(12, 'Venice Beach Skatepark', 'sports', 0.00, 'Visit the famous Venice Beach Skatepark and watch professional skaters.'),
(13, 'Gondola Ride', 'beach', 50.00, 'Take a romantic gondola ride through the canals of Venice.'),
(13, 'Rialto Market Visit', 'shopping', 20.00, 'Visit the bustling Rialto Market and try local Venetian delicacies.'),
(14, 'Taj Mahal Visit', 'sightseeing', 25.00, 'Visit the Taj Mahal and explore the history behind this world wonder.'),
(14, 'Agra Fort Tour', 'historical', 15.00, 'Tour the Agra Fort, a UNESCO World Heritage site with rich Mughal history.'),
(15, 'Surfing in Bali', 'adventure', 40.00, 'Catch waves and surf the famous beaches of Bali.'),
(15, 'Visit Uluwatu Temple', 'cultural', 20.00, 'Explore Uluwatu Temple, perched on a clifftop with ocean views.'),
(16, 'Great Barrier Reef Snorkeling', 'adventure', 120.00, 'Snorkel the Great Barrier Reef and explore its vibrant marine life.'),
(16, 'Daintree Rainforest Tour', 'nature', 90.00, 'Tour the Daintree Rainforest and explore Australia’s ancient ecosystems.'),
(17, 'Grand Canyon Helicopter Tour', 'adventure', 200.00, 'Take a helicopter tour over the majestic Grand Canyon.'),
(17, 'Hiking in Grand Canyon National Park', 'adventure', 0.00, 'Hike through the Grand Canyon and experience its vast beauty.'),
(18, 'Universal Studios Osaka', 'entertainment', 75.00, 'Visit Universal Studios in Osaka for thrilling rides and attractions.'),
(18, 'Osaka Castle Visit', 'historical', 20.00, 'Explore Osaka Castle and its surrounding gardens.'),
(19, 'Souks Shopping in Marrakech', 'shopping', 30.00, 'Wander through the colorful souks of Marrakech and shop for local goods.'),
(19, 'Jardin Majorelle Tour', 'nature', 15.00, 'Visit the beautiful Jardin Majorelle, a garden in the heart of Marrakech.'),
(20, 'Bungee Jumping in Queenstown', 'adventure', 200.00, 'Experience an adrenaline rush with bungee jumping in Queenstown.'),
(20, 'Skyline Gondola Ride', 'sightseeing', 35.00, 'Ride the Skyline Gondola and enjoy panoramic views of Queenstown.'),
(21, 'Snorkeling in Cancun', 'adventure', 40.00, 'Snorkel the vibrant coral reefs off the coast of Cancun.'),
(21, 'Chichen Itza Visit', 'historical', 50.00, 'Tour the ancient Mayan city of Chichen Itza, one of the New Seven Wonders.'),
(22, 'West End Show in London', 'entertainment', 100.00, 'Watch a world-class West End show in the heart of London.'),
(22, 'The British Museum Tour', 'museum', 0.00, 'Explore the British Museum and its incredible collection of artifacts.'),
(23, 'Sunset in Santorini', 'nature', 0.00, 'Watch a stunning sunset over the caldera in Santorini.'),
(23, 'Explore Oia Village', 'shopping', 20.00, 'Walk through Oia and enjoy its charming shops and restaurants.'),
(24, 'Old Quarter Walk in Hanoi', 'cultural', 0.00, 'Wander through Hanoi’s historic Old Quarter, a bustling market area.'),
(24, 'Hoan Kiem Lake Visit', 'nature', 0.00, 'Visit Hoan Kiem Lake and relax by its tranquil waters.'),
(25, 'Safari in Nairobi National Park', 'nature', 150.00, 'Go on a safari and spot wildlife like lions and giraffes in Nairobi National Park.'),
(25, 'David Sheldrick Wildlife Trust Visit', 'nature', 25.00, 'Visit the David Sheldrick Wildlife Trust and learn about elephant conservation.');

INSERT INTO reviews (destination_id, rating, review) VALUES
(1, 5, 'Paris is beautiful in the spring, with great views from the Eiffel Tower.'),
(1, 4, 'Loved the sights but it was crowded in peak season.'),
(2, 5, 'Kyoto is magical, especially during cherry blossom season.'),
(2, 4, 'Amazing temples, but can be crowded during peak times.'),
(3, 4, 'Sydney has vibrant beaches and culture. Bondi Beach was a highlight.'),
(3, 5, 'Opera House is a must-see and the beaches are great for surfing.'),
(4, 5, 'Rome is packed with history; the Colosseum is awe-inspiring.'),
(4, 4, 'The Vatican Museums are fascinating but expect long lines.'),
(5, 5, 'New York is thrilling with so much to see, especially Central Park.'),
(5, 4, 'Broadway shows are amazing, but tickets can be pricey.'),
(6, 5, 'Bangkok is vibrant, with so much to see and do, especially the Grand Palace.'),
(6, 4, 'Street food is amazing, but be careful of the spice levels!'),
(7, 5, 'Rio de Janeiro is stunning, especially the views from Christ the Redeemer.'),
(7, 4, 'Carnival is an unforgettable experience, though very crowded.'),
(8, 5, 'Barcelona has a perfect mix of beaches and history. La Sagrada Familia is beautiful.'),
(8, 5, 'The beaches in Barcelona are some of the best I’ve ever visited.'),
(9, 5, 'Vancouver is surrounded by natural beauty; Stanley Park is a must-see.'),
(9, 4, 'Whale watching was an incredible experience, but be prepared for early mornings.'),
(10, 5, 'Cape Town is breathtaking, and hiking up Table Mountain was a highlight.'),
(10, 5, 'Cape Point was amazing, with stunning views of the ocean meeting the land.'),
(11, 5, 'Cairo is a history lover’s dream; the pyramids and Sphinx are mind-blowing.'),
(11, 4, 'The Nile cruise was peaceful, but the weather can be very hot in summer.'),
(12, 5, 'LA is lively and full of surprises. Hollywood is definitely worth visiting.'),
(12, 4, 'Venice Beach is fun but a little touristy. Still, a must-see in LA.'),
(13, 5, 'Venice is a romantic destination with stunning canals and charming streets.'),
(13, 5, 'The gondola ride was unforgettable. A great way to explore Venice.'),
(14, 5, 'The Taj Mahal is awe-inspiring. A must-see if you’re in India.'),
(14, 4, 'The heat in Agra can be overwhelming, but the Taj Mahal is worth it.'),
(15, 5, 'Bali is paradise! The beaches and temples are stunning.'),
(15, 4, 'Uluwatu Temple offers a great view, but can get crowded.'),
(16, 5, 'The Great Barrier Reef is beyond amazing, one of the best snorkeling experiences ever.'),
(16, 5, 'Daintree Rainforest tour was incredible and felt like stepping into a magical world.'),
(17, 5, 'Grand Canyon is a natural wonder. The helicopter tour gave a unique perspective.'),
(17, 5, 'Hiking in the Grand Canyon was challenging but incredibly rewarding.'),
(18, 5, 'Osaka is a fun city with lots of energy. Universal Studios was fantastic.'),
(18, 5, 'Osaka Castle is impressive and rich in history. A must-see.'),
(19, 5, 'Marrakech is so full of life, from the souks to the palaces.'),
(19, 4, 'The Jardin Majorelle was peaceful, but it can get very crowded.'),
(20, 5, 'Queenstown is perfect for adventure lovers. The bungee jumping was thrilling!'),
(20, 5, 'Skyline Gondola offered amazing views of Queenstown and the surrounding areas.'),
(21, 5, 'Cancun has beautiful beaches and amazing coral reefs. Great for snorkeling.'),
(21, 5, 'Chichen Itza was a powerful experience, walking among the ancient ruins.'),
(22, 5, 'London is a vibrant city, full of history and excitement. West End shows are a must-see.'),
(22, 4, 'The British Museum is fantastic, but it can be overwhelming with so much to see.'),
(23, 5, 'Santorini is magical, especially at sunset. Perfect for a romantic getaway.'),
(23, 5, 'Oia is picturesque, with stunning views and great shopping.'),
(24, 5, 'Hanoi’s Old Quarter is so lively, and the food is amazing.'),
(24, 4, 'Hoan Kiem Lake is peaceful, but the surrounding area can get busy.'),
(25, 5, 'Nairobi offers incredible wildlife experiences, especially in the national parks.'),
(25, 5, 'The David Sheldrick Wildlife Trust is a heartwarming visit, supporting elephant conservation.');


select * from destinations;

select * from activities;

select * from reviews;